name: Deploy GitHub Pages
description: |
  Should be used in a job which has access to deploy.

inputs:
  directory:
    description: Directory (eg. docs_build, build) to be deployed as GitHub Pages
    required: false
    default: build

runs:
  using: "composite"
  steps:
    - name: Upload build Directory
      uses: actions/upload-pages-artifact@v3
      with:
        path: ${{ inputs.directory }}

    - name: Deploy build Directory to GitHub Pages
      uses: actions/deploy-pages@v4
